// <auto-generated />
using System;
using DreamRosterBuilding.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamRosterBuilding.Data.Migrations
{
    [DbContext(typeof(DreamRosterBuildingDbContext))]
    [Migration("20241029201538_AddedSettingEntity")]
    partial class AddedSettingEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.FlagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(8282),
                            ImagePath = "images/flags/Flag_of_Turkey.png",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(8292),
                            Name = "Turkiye"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(8296),
                            ImagePath = "images/flags/Flag_of_Spain.png",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(8296),
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.IconEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HairColor")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skin")
                        .HasColumnType("int");

                    b.Property<int?>("Tattoo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(9536),
                            HairColor = 0,
                            ImagePath = "images/icons/icon-default.png",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 809, DateTimeKind.Local).AddTicks(9539),
                            Name = "BlackHairMediumSkinNoTattoo",
                            Skin = 1
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.LeagueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(1389),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(1391),
                            Name = "Süper Lig",
                            NationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(1393),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(1393),
                            Name = "LaLiga",
                            NationId = 2
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.NationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FlagId")
                        .IsUnique();

                    b.ToTable("Nations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(3943),
                            FlagId = 1,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(3945),
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(3947),
                            FlagId = 2,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(3947),
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HairColor")
                        .HasColumnType("int");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NationId")
                        .HasColumnType("int");

                    b.Property<int>("Skin")
                        .HasColumnType("int");

                    b.Property<int?>("Tattoo")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("NationId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(5873),
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(5879),
                            CreatedUser = "admin",
                            HairColor = 0,
                            IconId = 1,
                            IsDeleted = false,
                            LeagueId = 1,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(5879),
                            ModifiedUser = "admin",
                            Name = "Mert Topcu",
                            NationId = 1,
                            Skin = 1,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerPositionEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerPositions");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PositionId = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(7424),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 810, DateTimeKind.Local).AddTicks(7427)
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerSkillEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerSkills");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            SkillId = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(156),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(159)
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(2554),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(2557),
                            Name = "GK"
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.SettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("MaintenanceMood")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MaintenanceMood = false,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.SkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(3596),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(3598),
                            Name = "Keeping"
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("NationId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4724),
                            CreatedUser = "admin",
                            Image = "images/teams/Fenerbahce.png",
                            IsDeleted = false,
                            LeagueId = 1,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4726),
                            ModifiedUser = "admin",
                            Name = "Fenerbahçe",
                            NationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4729),
                            CreatedUser = "admin",
                            Image = "images/teams/Galatasaray.png",
                            IsDeleted = false,
                            LeagueId = 1,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4729),
                            ModifiedUser = "admin",
                            Name = "Galatasaray",
                            NationId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4731),
                            CreatedUser = "admin",
                            Image = "images/teams/Real_Madrid.png",
                            IsDeleted = false,
                            LeagueId = 2,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4731),
                            ModifiedUser = "admin",
                            Name = "Real Madrid",
                            NationId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4733),
                            CreatedUser = "admin",
                            Image = "images/teams/Barcelona.png",
                            IsDeleted = false,
                            LeagueId = 2,
                            ModifiedDate = new DateTime(2024, 10, 29, 23, 15, 37, 811, DateTimeKind.Local).AddTicks(4734),
                            ModifiedUser = "admin",
                            Name = "Barcelona",
                            NationId = 2
                        });
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.LeagueEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.NationEntity", "Nation")
                        .WithMany("Leagues")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.NationEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.FlagEntity", "Flag")
                        .WithOne("Nation")
                        .HasForeignKey("DreamRosterBuilding.Data.Entities.NationEntity", "FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.IconEntity", "Icon")
                        .WithMany("Players")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.LeagueEntity", "League")
                        .WithMany("Players")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.NationEntity", "Nation")
                        .WithMany("Players")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.TeamEntity", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("League");

                    b.Navigation("Nation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerPositionEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.PlayerEntity", "Player")
                        .WithMany("PlayerPositions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.PositionEntity", "Position")
                        .WithMany("PlayerPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerSkillEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.PlayerEntity", "Player")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.SkillEntity", "Skill")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.TeamEntity", b =>
                {
                    b.HasOne("DreamRosterBuilding.Data.Entities.LeagueEntity", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DreamRosterBuilding.Data.Entities.NationEntity", "Nation")
                        .WithMany("Teams")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.FlagEntity", b =>
                {
                    b.Navigation("Nation")
                        .IsRequired();
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.IconEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.LeagueEntity", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.NationEntity", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("Players");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("PlayerPositions");

                    b.Navigation("PlayerSkills");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.PositionEntity", b =>
                {
                    b.Navigation("PlayerPositions");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.SkillEntity", b =>
                {
                    b.Navigation("PlayerSkills");
                });

            modelBuilder.Entity("DreamRosterBuilding.Data.Entities.TeamEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
